on:
  push:
    branches:
    - main
    - dev
  workflow_dispatch:
    inputs:
      assemblyType:
        description: 'Assembly type'
        required: true
        type: choice
        options:
        - prod
        - develop

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Install Node
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 21

      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install dependencies
        run: npm ci

      - name: Build 
        run: | 
          if [ "${{ inputs.assemblyType }}" == "prod" ]; then
            echo "Build production"
            npm run build-prod
          elif [ "${{ inputs.assemblyType }}" == "develop" ]; then
            echo "Build develop"
            npm run build
          else
            echo "Build production"
            npm run build-prod
          fi

      - name: Upload build result
        uses: actions/upload-artifact@v3.1.3
        with:
          name: build
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build
        uses: actions/download-artifact@v2.1.1
        with:
          name: build
      - name: Deploy files to server
        uses: appleboy/scp-action@master
        with:
          host: umlaut-bmstu.me
          username: ubuntu
          key: ${{ secrets.SHH_KEY }}
          source: dist
          target: /home/ubuntu/front/2023_2_Umlaut
